server:
  port: 8083

spring:
  application:
    name: soccer-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://db:5432/kroaddy
    username: kroaddy
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.schema: DEBUG
    org.hibernate.engine.jdbc.env.internal: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

